version: '3.8'
services:
  typesense:
    image: typesense/typesense:0.21.0
    ports:
      - "8108:8108"
    environment:
      TYPESENSE_API_KEY: xyz
      TYPESENSE_DATA_DIR: /data/typesense
      TYPESENSE_ENABLE_CORS: "true"
    volumes:
      - typesense:/data/typesense

volumes:
  typesense:
    driver: local